MovieBundle\Entity\Movie:
    type: entity
    repositoryClass: MovieBundle\Repository\MovieRepository
    table: movie
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 255
        year:
            type: datetime
    manyToMany:
        tags:
            targetEntity: Tag
            inversedBy: movies
            joinTable:
                name: movie_tags
                joinColumns:
                    movie_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id
